name: pzero
channels:
  - anaconda
  - loop3d
  - conda-forge
  - defaults
dependencies:
  - anaconda::pyqt[version='>=5.15.10']
  - blackd[version='>=23.7.0']
  - cmocean
  - colorcet
  - ezdxf[version='>=1.0.3']
  - geopandas[version='>=0.11.1']
  - laspy[version='>=2.3.0']
  - libgdal[version='>=3.9.2']
  - loop3d::loopstructural[version='>=v1.6.1']
  - lxml[version='>=5.3.0']
  - mplstereonet[version='>=0.6.3']
  - matplotlib-base[version='<3.9']
  - pandas=1.5.3
  - pyinstaller[version='>=6']
  - pytest[version='>=7']
  - python[version='>=3.9']
  - pyvista[version='>=0.44.1']
  - pyvistaqt[version='>=0.11.1']
  - qtpy
  - rasterio[version='>=1.3.6']
  - seaborn
  - shapely[version='>=2.0.6']
  - sphinx[version='>=5']
  - sphinx_rtd_theme[version='>=2']
  - vedo
  - vtk-base[version='>=9.3.1']
  - vtk[version='>=9.3.1']
  - xarray[version='>=2023.1.0']
  