name: pzero
channels:
  - conda-forge
  - loop3d
  - defaults
dependencies:
  - python=3.8
  - blackd=24.8.0
  - cmocean=4.0.3
  - colorcet=3.1.0
  - ezdxf=1.3.0
  - geopandas=0.14.2
  - laspy=2.5.4
  - loopstructural=v1.6.1
  - lxml=5.3.0
  - mplstereonet=0.6.3
  - pyinstaller=6.10.0
  - pyqt=5.15.10
  - pytest=7.4.4
  - pyvistaqt=0.11.1
  - qtpy=2.4.1
  - rasterio=1.4.1
  - seaborn=0.13.2
  - shapely=2.0.6
  - sphinx=7.3.7
  - sphinx_rtd_theme=2.0.0
  - vedo=2024.5.1
  - vtk=9.3.1
  - xarray=2023.6.0
